export const countries = [
  { name: 'United Arab Emirates', currency: 'AED' },
  { name: 'United States', currency: 'USD' },
  { name: 'United Kingdom', currency: 'GBP' },
  { name: 'Saudi Arabia', currency: 'SAR' },
  { name: 'Qatar', currency: 'QAR' },
  { name: 'Oman', currency: 'OMR' },
  { name: 'Kuwait', currency: 'KWD' },
  { name: 'Bahrain', currency: 'BHD' },
  { name: 'India', currency: 'INR' },
  { name: 'Australia', currency: 'AUD' },
  { name: 'Canada', currency: 'CAD' },
  { name: 'European Union', currency: 'EUR' },
  { name: 'Japan', currency: 'JPY' },
  { name: 'China', currency: 'CNY' },
  { name: 'Singapore', currency: 'SGD' },
  { name: 'Malaysia', currency: 'MYR' },
  { name: 'New Zealand', currency: 'NZD' },
  { name: 'South Africa', currency: 'ZAR' },
  { name: 'Pakistan', currency: 'PKR' },
  { name: 'Bangladesh', currency: 'BDT' },
  { name: 'Egypt', currency: 'EGP' },
  { name: 'Lebanon', currency: 'LBP' },
  { name: 'Jordan', currency: 'JOD' },
  { name: 'Morocco', currency: 'MAD' },
  { name: 'Switzerland', currency: 'CHF' },
  { name: 'Sweden', currency: 'SEK' },
  { name: 'Norway', currency: 'NOK' },
  { name: 'Denmark', currency: 'DKK' },
  { name: 'Hong Kong', currency: 'HKD' },
  { name: 'South Korea', currency: 'KRW' },
  { name: 'Brazil', currency: 'BRL' },
  { name: 'Mexico', currency: 'MXN' },
  { name: 'Russia', currency: 'RUB' },
  { name: 'Turkey', currency: 'TRY' },
  { name: 'Argentina', currency: 'ARS' },
  { name: 'Nigeria', currency: 'NGN' },
  { name: 'Kenya', currency: 'KES' },
  { name: 'Indonesia', currency: 'IDR' },
  { name: 'Philippines', currency: 'PHP' },
  { name: 'Thailand', currency: 'THB' },
  { name: 'Vietnam', currency: 'VND' },
  { name: 'Sri Lanka', currency: 'LKR' },
  { name: 'Nepal', currency: 'NPR' }
].sort((a, b) => a.name.localeCompare(b.name));
